### ISSUE TITLE
failed on `network up` in sample network

### ISSUE THREAD

**Issue by bjwswang** [hyperledger-labs/fabric-operator#63]
![image](https://user-images.githubusercontent.com/30621793/197761286-e5bc1a81-a445-4fa0-9937-9fa30d7ea127.png)

succeeded in `network cluster init` ,but failed on `network up`.

Any thoughts? Thanks.

**Comment by bjwswang** [comment]
Pretty sure crds install when doing `network cluster init`

**Comment by skypos99** [comment]
Looks like fabric crds are not installed properly.run below command and check 
kubectl get crds

**Comment by bjwswang** [comment]
![image](https://user-images.githubusercontent.com/30621793/197911582-cb05627a-de90-4afa-af27-b10d9f9d5d84.png)
tried. crds installed...

**Comment by bjwswang** [comment]
When I tried `apply_operator` step by step,  I found error at`apply_kustomization config/rbac` .
![image](https://user-images.githubusercontent.com/30621793/197917395-efb13c9e-947e-4587-aa86-a65863fbf749.png)

BTW... using k8s with `kind`. seems `kind` do not support `PodSecurityPolicy`

**Comment by jkneubuh** [comment]
Thanks for digging in.  This is a real bug.  See Issue #50 for more details on the underlying problem.

A couple of weeks ago the k8s rev was updated from 1.24 to 1.25, and some of the RBAC mechanisms that had been deprecated have now been removed from the Kubernetes APIs.   The most recent builds of `kind` by default will install Kubernetes 1.25.x, which is causing the issues above.

Could you try patching the [creation of the KIND cluster](https://github.com/hyperledger-labs/fabric-operator/blob/main/sample-network/scripts/kind.sh#L36) to pin the k8s rev?    I think the script just needs a property that will pin the rev to 1.24.x.
 
```
KIND_CLUSTER_IMAGE=${KIND_CLUSTER_IMAGE:-kindest/node:v1.24.4}   

...
  cat << EOF | kind create cluster --name $KIND_CLUSTER_NAME --image $KIND_CLUSTER_IMAGE --config=-
```

Issue #50 needs to address whatever incompatibilities are preventing the operator from installing on a 1.25 k8s.  This ticket just needs to patch up the sample network script so that it keeps the KIND cluster at the older k8s revs.

**Comment by bjwswang** [comment]
@jkneubuh  this works on my laptop. Thanks! 
 A new property `KIND_CLUSTER_IMAGE=${KIND_CLUSTER_IMAGE:-kindest/node:v1.24.4} ` in script seems the better solutoin since kind only used in dev environment.

**Comment by jkneubuh** [comment]
Let's leave this open for now, as it will come up again when new users install `kind` and/or upgrade to the latest rev.

Thanks again for double-checking the approach.  Glad this worked out well - it is really nice that the KIND team has a solution for running older revs of k8s.

**Comment by jkneubuh** [comment]
`./network kind` now pins k8s to 1.24.0 by default.  This can be overridden with `TEST_NETWORK_CLUSTER_IMAGE=kindest/node:vX.YY.Z`
